### ISSUE TITLE
netlify build issue

### ISSUE THREAD

**Issue by Ayushman67** [cobidev/simplefolio#109]
11:12:52 PM: Build ready to start
11:12:54 PM: build-image version: 653805ca4a64301556e56dc4b321ef8fc20cbb7c
11:12:54 PM: build-image tag: v3.8.2
11:12:54 PM: buildbot version: 27121fae4d1b3a5c621e9bbd5ca8c7f99e19f330
11:12:54 PM: Fetching cached dependencies
11:12:54 PM: Failed to fetch cache, continuing with build
11:12:54 PM: Starting to prepare the repo for build
11:12:54 PM: No cached dependencies found. Cloning fresh repo
11:12:54 PM: git clone https://github.com/Ayushman67/portfolio-site
11:12:55 PM: Preparing Git Reference refs/heads/main
11:12:56 PM: Parsing package.json dependencies
11:12:56 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'dist' versus 'dist/' in the Netlify UI
11:12:57 PM: Starting build script
11:12:57 PM: Installing dependencies
11:12:57 PM: Python version set to 2.7
11:12:58 PM: v12.18.0 is already installed.
11:12:58 PM: Now using node v12.18.0 (npm v6.14.4)
11:12:59 PM: Started restoring cached build plugins
11:12:59 PM: Finished restoring cached build plugins
11:12:59 PM: Attempting ruby version 2.7.2, read from environment
11:13:00 PM: Using ruby version 2.7.2
11:13:00 PM: Using PHP version 5.6
11:13:00 PM: Started restoring cached node modules
11:13:00 PM: Finished restoring cached node modules
11:13:01 PM: Installing NPM modules using NPM version 6.14.4
11:13:03 PM: npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
11:13:03 PM: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
11:13:04 PM: npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
11:13:05 PM: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
11:13:05 PM: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
11:13:06 PM: npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
11:13:07 PM: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
11:13:10 PM: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
11:13:10 PM: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
11:13:20 PM: > node-sass@6.0.1 install /opt/build/repo/node_modules/node-sass
11:13:20 PM: > node scripts/install.js
11:13:21 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v6.0.1/linux-x64-72_binding.node
11:13:21 PM: Download complete
11:13:21 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
11:13:21 PM: Caching binary to /opt/buildhome/.npm/node-sass/6.0.1/linux-x64-72_binding.node
11:13:21 PM: > node-sass@6.0.1 postinstall /opt/build/repo/node_modules/node-sass
11:13:21 PM: > node scripts/build.js
11:13:22 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
11:13:22 PM: Testing binary
11:13:22 PM: Binary is fine
11:13:22 PM: npm notice created a lockfile as package-lock.json. You should commit this file.
11:13:22 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
11:13:22 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
11:13:22 PM: npm WARN optimize-css-assets-webpack-plugin@6.0.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
11:13:22 PM: added 753 packages from 476 contributors and audited 755 packages in 20.854s
11:13:23 PM: 62 packages are looking for funding
11:13:23 PM:   run `npm fund` for details
11:13:23 PM: found 1 moderate severity vulnerability
11:13:23 PM:   run `npm audit fix` to fix them, or `npm audit` for details
11:13:23 PM: NPM modules installed
11:13:23 PM: Started restoring cached go cache
11:13:23 PM: Finished restoring cached go cache
11:13:23 PM: go version go1.14.4 linux/amd64
11:13:23 PM: go version go1.14.4 linux/amd64
11:13:23 PM: Installing missing commands
11:13:23 PM: Verify run directory
11:13:24 PM: ​
11:13:24 PM: ────────────────────────────────────────────────────────────────
11:13:24 PM:   Netlify Build                                                 
11:13:24 PM: ────────────────────────────────────────────────────────────────
11:13:24 PM: ​
11:13:24 PM: ❯ Version
11:13:24 PM:   @netlify/build 17.9.2
11:13:24 PM: ​
11:13:24 PM: ❯ Flags
11:13:24 PM:   baseRelDir: true
11:13:24 PM:   deployId: 610d749cb5d12cf6ca5f5bb8
11:13:24 PM: ​
11:13:24 PM: ❯ Current directory
11:13:24 PM:   /opt/build/repo
11:13:24 PM: ​
11:13:24 PM: ❯ Config file
11:13:24 PM:   No config file was defined: using default values.
11:13:24 PM: ​
11:13:24 PM: ❯ Context
11:13:24 PM:   production
11:13:24 PM: ​
11:13:24 PM: ────────────────────────────────────────────────────────────────
11:13:24 PM:   1. Build command from Netlify app                             
11:13:24 PM: ────────────────────────────────────────────────────────────────
11:13:24 PM: ​
11:13:24 PM: $ npm run build
11:13:24 PM: > simplefolio@1.0.1 build /opt/build/repo
11:13:24 PM: > webpack --config webpack.prod.js
11:13:26 PM: (node:1350) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
11:13:37 PM: assets by status 571 KiB [cached] 11 assets
11:13:37 PM: Entrypoint vendor = vendor.6faef603b0d23fa3f710.bundle.js
11:13:37 PM: Entrypoint main = main.899af159c8cacda1b776.css main.0bb5a33f16ad2a8147de.bundle.js 1 auxiliary asset
11:13:37 PM: orphan modules 299 KiB [orphan] 67 modules
11:13:37 PM: runtime modules 1.72 KiB 5 modules
11:13:37 PM: cacheable modules 502 KiB (javascript) 166 KiB (css/mini-extract)
11:13:37 PM:   javascript modules 502 KiB
11:13:37 PM:     modules by path ./src/ 209 KiB
11:13:37 PM:       ./src/vendor.js + 56 modules 206 KiB [built] [code generated]
11:13:37 PM:       ./src/index.js + 6 modules 2.54 KiB [built] [code generated]
11:13:37 PM:     modules by path ./node_modules/ 293 KiB
11:13:37 PM:       ./node_modules/jquery/dist/jquery.js 282 KiB [built] [code generated]
11:13:37 PM:       ./node_modules/tilt.js/src/tilt.jquery.js 11.5 KiB [built] [code generated]
11:13:37 PM:   modules by path ./src/style/ 166 KiB
11:13:37 PM:     css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/style/main.scss 72 bytes [built] [code generated]
11:13:37 PM:     css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/style/main.scss (1) 166 KiB [built] [code generated]
11:13:37 PM: ERROR in   Error: Child compilation failed:
11:13:37 PM:   Module not found: Error: Can't resolve './assets/Karkinos.jpg' in '/opt/build/  repo/src'
  ModuleNotFoundError: Module not found: Error: Can't resolve './assets/Karkinos  .jpg' in '/opt/build/repo/src'
      at /opt/build/repo/node_modules/webpack/lib/Compilation.js:1773:28
11:13:37 PM:       at /opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:811:13
11:13:37 PM:       at eval (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCode  Factory.js:33:10), <anonymous>:8:1)
11:13:37 PM:       at /opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:286:22
11:13:37 PM:       at eval (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCode  Factory.js:33:10), <anonymous>:7:1)
11:13:37 PM:       at /opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:442:22
11:13:37 PM:       at /opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:124:11
11:13:37 PM:       at /opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:673:25
11:13:37 PM:       at /opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:882:8
11:13:37 PM:       at /opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
11:13:37 PM:   - Compilation.js:1773
11:13:37 PM:     [repo]/[webpack]/lib/Compilation.js:1773:28
11:13:37 PM:   - NormalModuleFactory.js:811
11:13:37 PM:     [repo]/[webpack]/lib/NormalModuleFactory.js:811:13
11:13:37 PM:   - NormalModuleFactory.js:286
11:13:37 PM:     [repo]/[webpack]/lib/NormalModuleFactory.js:286:22
11:13:37 PM:   - NormalModuleFactory.js:442
11:13:37 PM:     [repo]/[webpack]/lib/NormalModuleFactory.js:442:22
11:13:37 PM:   - NormalModuleFactory.js:124
11:13:37 PM:     [repo]/[webpack]/lib/NormalModuleFactory.js:124:11
11:13:37 PM:   - NormalModuleFactory.js:673
11:13:37 PM:     [repo]/[webpack]/lib/NormalModuleFactory.js:673:25
11:13:37 PM:   - NormalModuleFactory.js:882
11:13:37 PM:     [repo]/[webpack]/lib/NormalModuleFactory.js:882:8
11:13:37 PM:   - NormalModuleFactory.js:1002
11:13:37 PM:     [repo]/[webpack]/lib/NormalModuleFactory.js:1002:5
11:13:37 PM:   - child-compiler.js:169
11:13:37 PM:     [repo]/[html-webpack-plugin]/lib/child-compiler.js:169:18
11:13:37 PM:   - Compiler.js:548
11:13:37 PM:     [repo]/[webpack]/lib/Compiler.js:548:11
11:13:37 PM:   - Compiler.js:1118
11:13:37 PM:     [repo]/[webpack]/lib/Compiler.js:1118:17
11:13:37 PM:   - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
11:13:37 PM:     [repo]/[tapable]/lib/Hook.js:18:14
11:13:37 PM:   - Compiler.js:1114
11:13:37 PM:     [repo]/[webpack]/lib/Compiler.js:1114:33
11:13:37 PM:   - Compilation.js:2254 finalCallback
11:13:37 PM:     [repo]/[webpack]/lib/Compilation.js:2254:11
11:13:37 PM:   - Compilation.js:2545
11:13:37 PM:     [repo]/[webpack]/lib/Compilation.js:2545:11
11:13:37 PM:   - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
11:13:37 PM:     [repo]/[tapable]/lib/Hook.js:18:14
11:13:37 PM: 
11:13:37 PM: 1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
11:13:37 PM: webpack 5.49.0 compiled with 2 errors in 11188 ms
11:13:37 PM: npm ERR! code ELIFECYCLE
11:13:37 PM: npm ERR! errno 1
11:13:37 PM: npm ERR! simplefolio@1.0.1 build: `webpack --config webpack.prod.js`
11:13:37 PM: npm ERR! Exit status 1
11:13:37 PM: npm ERR!
11:13:37 PM: npm ERR! Failed at the simplefolio@1.0.1 build script.
11:13:37 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:13:37 PM: npm ERR! A complete log of this run can be found in:
11:13:37 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-08-06T17_43_37_603Z-debug.log
11:13:37 PM: ​
11:13:37 PM: ────────────────────────────────────────────────────────────────
11:13:37 PM:   "build.command" failed                                        
11:13:37 PM: ────────────────────────────────────────────────────────────────
11:13:37 PM: ​
11:13:37 PM:   Error message
11:13:37 PM:   Command failed with exit code 1: npm run build
11:13:37 PM: ​
11:13:37 PM:   Error location
11:13:37 PM:   In Build command from Netlify app:
11:13:37 PM:   npm run build
11:13:37 PM: ​
11:13:37 PM:   Resolved config
11:13:37 PM:   build:
11:13:37 PM:     command: npm run build
11:13:37 PM:     commandOrigin: ui
11:13:37 PM:     publish: /opt/build/repo/dist
11:13:37 PM:     publishOrigin: ui
11:13:38 PM: Caching artifacts
11:13:38 PM: Started saving node modules
11:13:38 PM: Finished saving node modules
11:13:38 PM: Started saving build plugins
11:13:38 PM: Finished saving build plugins
11:13:38 PM: Started saving pip cache
11:13:38 PM: Finished saving pip cache
11:13:38 PM: Started saving emacs cask dependencies
11:13:38 PM: Finished saving emacs cask dependencies
11:13:38 PM: Started saving maven dependencies
11:13:38 PM: Finished saving maven dependencies
11:13:38 PM: Started saving boot dependencies
11:13:38 PM: Finished saving boot dependencies
11:13:38 PM: Started saving rust rustup cache
11:13:38 PM: Finished saving rust rustup cache
11:13:38 PM: Started saving go dependencies
11:13:38 PM: Finished saving go dependencies
11:13:41 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:13:41 PM: Creating deploy upload records
11:13:41 PM: Failing build: Failed to build site
11:13:41 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
11:13:41 PM: Finished processing build request in 46.976670181s

so whenever i am pushing the changes this is the issue that i am getting. the site gets deployed without the changes, but once it detects the changes it throws this error. Please help

**Comment by terrysu64** [comment]
I ran into the same issue. Instead of using Netlify, I ran "npm run build" locally instead and deployed it successfully via. GitHub pages.

**Comment by Gauthamyadav777** [comment]
> I ran into the same issue. Instead of using Netlify, I ran "npm run build" locally instead and deployed the website successfully via. GitHub pages.

Can you show me a walkthrough of how you have done it pls dude? Thanks

**Comment by terrysu64** [comment]
Sure, do you have Discord or Instagram by any chance? We could schedule a call sometime and I can try to help if you'd like?

**Comment by ezechuka** [comment]
I'm facing the same issue & and I need your help @terrysu64 too

**Comment by terrysu64** [comment]
@ezechuka dm me on Discord (my tag: txrry_#5882) or Instagram (@txrry___). I could try and help that way

**Comment by im-coder-lg** [comment]
@ezechuka what @terrysu64 meant is that you clone the repo locally with Git or GitHub CLI, then use Node JS's NPM(Node Package Manager) to get dependencies(npm install) and then building Simplefolio via `npm run build`. You need Git and Node JS. After building, push the built files to GitHub. Assuming you know that but if you don't, follow this(total guide):
```bash
git clone repo-git-url
cd the-repo
npm install
npm run build
git add -A
git commit -m "commit-msg"
git push
```
That's all you need to follow totally.

**NOTE**: Remember to switch `repo-git-url` with your repo git url(found inside the `Code` section and inside the `Code` button) and `the-repo` with your repo name.

**Comment by Gauthamyadav777** [comment]
> Sure, do you have Discord or Instagram by any chance? We could schedule a call sometime and I can try to help if you'd like?

I have figured out the issue and deployed through Netlify. Thanks anyway. :)

**Comment by terrysu64** [comment]
Ok, glad to know 👌

**Comment by Alikaname** [comment]
> I have figured out the issue and deployed through Netlify. Thanks anyway. :)

how did you fix the issue on netlify?

**Comment by Gauthamyadav777** [comment]
> > I have figured out the issue and deployed through Netlify. Thanks anyway. :)
> 
> how did you fix the issue on netlify?

https://answers.netlify.com/t/page-not-found-looks-like-youve-followed-a-broken-link-my-index-html-file-does-not-upload-on-netlify-when-deployed/43932/8?u=gauthamyadav777
