### ISSUE TITLE
Profile Image

### ISSUE THREAD

**Issue by troygolden** [cobidev/simplefolio#12]
For some reason, i cant get the profile image to show.

**Comment by abonmassip** [comment]
I'm having the same problem, and not only the profile image but all images are not showing. The weird thing is it was working before, I could see the default images, but as soon as I tried adding my profile image all the images broke. And now even if I delete everything and start again step by step using the guide it doesn't work.

![Annotation 2019-12-09 181539](https://user-images.githubusercontent.com/57193513/70489225-ee6de580-1aaf-11ea-8ef2-2916ee269da1.jpg)

if I right click the missing image and select "View Image" I get this page
![Annotation 2019-12-09 181647](https://user-images.githubusercontent.com/57193513/70489313-43116080-1ab0-11ea-8478-f6be35d6af3c.jpg)

**Comment by abonmassip** [comment]
I attach also what I get on the terminal after running npm start
![Annotation 2019-12-09 183041](https://user-images.githubusercontent.com/57193513/70490065-44438d00-1ab2-11ea-9343-96c6c168ad39.jpg)

I don't understand why suddenly it doesn't work anymore. I would really appreciate some help

**Comment by alexmonteil** [comment]
I'm having the same issue, none of the pictures show.

I'm a bit busy these days, but if I have time I'll try to fork, fix and submit a PR in the next few days.

If someone does it earlier than that, even better !

**Comment by alexmonteil** [comment]
It is most likely the file loader package update from 4.2.0 to 5.0.2 that broke the app.

For the time being, until someone fixes it, if you need the portfolio to work right now just change the following package versions in your package.json file to the following :

"css-loader": "^3.2.0"

"file-loader": "^4.2.0"

"style-loader": "^1.0.0"

"bootstrap": "^4.3.1"

**Comment by amberchisholm** [comment]
I'm having the same issues. None of the pictures, or any of the CSS shows up. Even after following the README and installing using sudo, no dice. Also getting a ton of console errors when loaded into my browser....mostly about "Cannot find module 'node-sass'.

**Comment by amberchisholm** [comment]
Nevermind...I got it working. Needed to run this command in my terminal

sudo npm install --save-dev  --unsafe-perm node-sass

**Comment by troygolden** [comment]
It works changing the package.json file versions...

**Comment by mahmutsen** [comment]
![Screenshot from 2020-02-05 18-55-55](https://user-images.githubusercontent.com/32749077/73858342-4bd0a980-4849-11ea-8995-b7f6cf61ecd6.png)
I've tried all the solutions mentioned there. I guess problem about being Linux 64-bit with Node.js 12.x
![Screenshot from 2020-02-05 18-55-03](https://user-images.githubusercontent.com/32749077/73858656-cbf70f00-4849-11ea-92b7-77fb35b1cc02.png)

**Comment by cobidev** [comment]
@abonmassip @troygolden @amberchisholm @alexmonteil hello!

Sorry for coming late in order to solve this issue. As Alex said, I update some packages in December, so webpack started to crash because the config was not following some parameters to have working the file-loader.

`{
    loader: "file-loader",
    options: {
      name: "[name].[hash].[ext]",
      outputPath: "assets",
      esModule: false // <- I needed to add this prop
    }
  }
`

For the time being, the project is working 🙂
