### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by ganeshblaze** [cobidev/simplefolio#13]
hey Jacob,

first of all beautiful portfolio template, I
![Screenshot (79)](https://user-images.githubusercontent.com/41594037/71201941-1edc2d80-22c1-11ea-8445-53aa80a3bbe5.png)
 badly needed this. But i am having issue deploying to Heroku pls give me the solution asap. The more detailed solution would be helpful

**Comment by cobidev** [comment]
Hello @ganeshblaze 

Heroku has a different setup for deployment. Need some Node.js setup.

I used Netlify just to keep it simple. And for this case (static portfolio) it is not necessary to use Heroku because it will add more complexity on the source code.
