### ISSUE TITLE
Changing Favicon

### ISSUE THREAD

**Issue by DerekShig** [cobidev/simplefolio#14]
Anyone else have an issue changing the title icon? Can't seem to change it.

**Comment by cobidev** [comment]
Hello @DerekShig how are you?

I just tested and I changed the title icon properly.

Steps to reproduce:
- Go to src/assets
- Replace the default favicon.png for other of convenience. I used a 512px / 512px png image.
- Start your development server, if the icon doesnt update, do a hard refresh comand + R or ctr + R if you're on Windows.

Let me know if with that works!

**Comment by aditya2712** [comment]
> Hello @DerekShig how are you?
> 
> I just tested and I changed the title icon properly.
> 
> Steps to reproduce:
> 
> * Go to src/assets
> * Replace the default favicon.png for other of convenience. I used a 512px / 512px png image.
> * Start your development server, if the icon doesnt update, do a hard refresh command + R or ctr + R if you're on Windows.
> 
> Let me know if with that works!

Yes It works perfectly
