### ISSUE TITLE
Background image from hero section won't be added to dist

### ISSUE THREAD

**Issue by createNull** [cobidev/simplefolio#17]
Hello Jacob, 

There is  the posibility of adding a background image with url() in css for the hero section, but you forgot to add the rule in webpack common.

**Comment by createNull** [comment]
Ok, it worked in the end.
So, the trick is to use a relative path for the url() in your css file:

Replace `background: url("/src/assets/[your-image].png");` with `background: url("../assets/[your-image].png");`

**Comment by aokdirova** [comment]
Thank you so much! I was going crazy whole day with this problem. Saved me
