### ISSUE TITLE
Changing the white background of the landing page (hero section) with background: url() is not recognised by netlify

### ISSUE THREAD

**Issue by frankoadeleye** [cobidev/simplefolio#19]
Whenever I uncomment the background: url () in the style/section/_hero.scss line 18-22 or thereabout and I use an image there, it works quite well on my localhost with npm start, but doesn't come on when I reload on netlify... Can you pls help out. 
Thanks so much

**Comment by frankoadeleye** [comment]
After several hours of fruastration (lol), I got it to work, by removing the quotes from the url(), i.e. changing url("") to url().
Thanks everyone, might be helpful to someone

**Comment by sotomaque** [comment]
hey did you manage to change the background to an image?

**Comment by sotomaque** [comment]
if so can you post the css / scss

**Comment by frankoadeleye** [comment]
In your _hero.scss, under hero id:
```
background: linear-gradient(to bottom, rgba(0,0,0,.7), rgba(0,0,0,.7)),  url(../assets/background.jpg) center no-repeat;
  background-attachment: fixed;
  background-size: cover;
```

**Comment by frankoadeleye** [comment]
Also if you're having problem getting your resume to showup when you click the view resume button, this worked for me:
In your template.html
```
<a target="_blank" class="cta-btn cta-btn--resume" href="./assets/nameofpdfifle.pdf">
                  View Resume
                </a>
```
then in your index.js: 
(1.) import the resume
```
import MyResume from './assets/FranksResume2020.pdf';
```
(2.)Then modify the addResume function like this, using whatever name of your resume as parameter(in my case, I named it MyResume as you can see):
```
function addResume(MyResume){
  const elements = document.getElementsByClassName('.cta-btn--resume');
  for(let el of elements){
    el.href = url(MyResume);
  }
}
```

**Comment by maryjane08** [comment]
> After several hours of fruastration (lol), I got it to work, by removing the quotes from the url(), i.e. changing url("") to url().
> Thanks everyone, might be helpful to someone

yes thanks

**Comment by neerajpsingh** [comment]
> In your _hero.scss, under hero id: (don't include quotes in your url( ) )
> 
> ```
> background: linear-gradient(to bottom, rgba(0,0,0,.7), rgba(0,0,0,.7)),  url(../assets/background.jpg) center no-repeat;
>   background-attachment: fixed;
>   background-size: cover;
> ```

Bro, I am not getting even then.Can u plz help me out
