### ISSUE TITLE
The Link in the footer of the demo site has a missing letter

### ISSUE THREAD

**Issue by pvptowers** [cobidev/simplefolio#22]
Hi 

The link in the footer of the demo site that goes to your github is broken.

Where you have "Template developed by Jacobo Martínez" it links to https://github.com/covidev 

I.e. it's missing the "b" in your username
Paul

**Comment by cobidev** [comment]
Hi Paul! Hope you're doing well.

Thank you for notice that 🙌

Commit: https://github.com/cobidev/simplefolio/commit/0f73e845f9edde41eaeae59f4e5405e8201286fc
