### ISSUE TITLE
Change favicon 

### ISSUE THREAD

**Issue by MarioAvolio** [cobidev/simplefolio#272]
Hi, how i can change the favicon using:

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
```

netlify give me builing error

**Comment by yw1101** [comment]
Hi, if you just want to change the favicon using, I would like to recommend you to change the name of the png and run it again, which works for me.

**Comment by MarioAvolio** [comment]
no i want to change the facivon

> Hi, if you just want to change the favicon using, I would like to recommend you to change the name of the png and run it again, which works for me.

no i want to change the favicon using the standard approach
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
```

because in this repository we use this code for selecting favicon: 
`  <link rel="shortcut icon" type="image/png" href="assets/favicon.png" />
`

but it gives some problems when i visualzie the page on google

**Comment by MarioAvolio** [comment]
this is the output in builing:

11:12:51 AM: Netlify Build                                                 
11:12:51 AM: ────────────────────────────────────────────────────────────────
11:12:51 AM: ​
11:12:51 AM: ❯ Version
11:12:51 AM:   @netlify/build 29.21.1
11:12:51 AM: ​
11:12:51 AM: ❯ Flags
11:12:51 AM:   baseRelDir: true
11:12:51 AM:   buildId: 650d5a5d224d3d000885ad42
11:12:51 AM:   deployId: 650d5a5d224d3d000885ad44
11:12:51 AM: ​
11:12:51 AM: ❯ Current directory
11:12:51 AM:   /opt/build/repo
11:12:51 AM: ​
11:12:51 AM: ❯ Config file
11:12:51 AM:   No config file was defined: using default values.
11:12:51 AM: ​
11:12:51 AM: ❯ Context
11:12:51 AM:   production
11:12:51 AM: ​
11:12:51 AM: ❯ Loading plugins
11:12:51 AM:    - @netlify/plugin-lighthouse@4.1.1 from Netlify app
11:12:51 AM: ​
11:12:51 AM: ❯ Outdated plugins
11:12:51 AM:    - @netlify/plugin-lighthouse@4.1.1: latest version is 5.0.0
11:12:51 AM:      To upgrade this plugin, please uninstall and re-install it from the Netlify plugins directory (https://app.netlify.com/plugins)
11:12:52 AM: ​
11:12:52 AM: Build command from Netlify app                                
11:12:52 AM: ────────────────────────────────────────────────────────────────
11:12:52 AM: ​
11:12:52 AM: $ npm run build
11:12:52 AM: > simplefolio@1.0.1 build
11:12:52 AM: > parcel build
11:12:53 AM: Building...
11:12:53 AM: console: Browserslist: caniuse-lite is outdated. Please run:
11:12:53 AM:   npx update-browserslist-db@latest
11:12:53 AM:   Why you should do it regularly: 
11:12:53 AM: https://github.com/browserslist/update-db#readme
11:12:56 AM: 🚨 Build failed.
11:12:56 AM: @parcel/core: Failed to resolve '.../icons8-artificial-intelligence-16.png' from
11:12:56 AM:  './src/index.html'
11:12:56 AM: @parcel/resolver-default: Cannot load file
11:12:56 AM: './.../icons8-artificial-intelligence-16.png' in './src'.
11:12:56 AM: ​
11:12:56 AM: build.command failed                                        
11:12:56 AM: ────────────────────────────────────────────────────────────────
11:12:56 AM: ​
11:12:56 AM:   Error message
11:12:56 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
11:12:56 AM: ​
11:12:56 AM:   Error location
11:12:56 AM:   In Build command from Netlify app:
11:12:56 AM:   npm run build
11:12:56 AM: ​
11:12:56 AM:   Resolved config
11:12:56 AM:   build:
11:12:56 AM:     command: npm run build
11:12:56 AM:     commandOrigin: ui
11:12:56 AM:     publish: /opt/build/repo/dist
11:12:56 AM:     publishOrigin: ui
11:12:56 AM:   plugins:
11:12:56 AM:     - inputs: {}
11:12:56 AM:       origin: ui
11:12:56 AM:       package: '@netlify/plugin-lighthouse'
11:12:57 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:12:57 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:12:57 AM: Failing build: Failed to build site
11:12:57 AM: Finished processing build request in 31.738s
