### ISSUE TITLE
Multi language portfolio error

### ISSUE THREAD

**Issue by Erwan-ui** [cobidev/simplefolio#34]
Hi man, thanks a lot for this super portfolio! 
So basically what i wanted to do was to enable the possibility to switch the site from english to french, so I added two buttons and i duplicated the html and then translated it and then link the button to the translated html, so i can switch between the two. 
For a long time it didn't work but then i understood there was an issu with webpack, who only knew about template.html. So i created new webpack html plugins for template_french.html and it works locally.
Now the problem is that when i deploy the site, as you said, on netlify, when i click on the FR button i get an error: Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

I kind of think it has something to do with the dist folder not knowing about my translated page but i have no idea how to fix it. Can you help me??? Thanks a lot!

**Comment by cobidev** [comment]
Hello @Erwan-ui 

Did you be able to solve it?

If not, I can start thinking about adding this as a feature.

Remember that this version is super simple, so adding different translation may be kinda odd (creating another HTML file).
