### ISSUE TITLE
Resume addition

### ISSUE THREAD

**Issue by aditya2712** [cobidev/simplefolio#48]
Is anyone else facing an issue while linking resume pdf. It is showing error 404. Even though I checked the location of the pdf but could not resolve it .

**Comment by abhi526691** [comment]
@aditya2712  upload your resume into drive and add that link into href tag into resume button thts it....

**Comment by hadi-mirza** [comment]
Apologies if it's redundant but this is my solution from another issue in this repo:

I've only tested this on Chrome.

1. Add this in gatsby-config inside plugins array with the other resolve objects:
```
   {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'pdf',
        path: '${__dirname}/src/pdf/',
      },
    },
```

2. Create directory in `src` folder called `pdf` and drop your resume in there: `/src/pdf/My-Resume.pdf`
3. In `/src/Components/About/About.jsx` add to the top of the page: `import File from '../../pdf/My-Resume.pdf'`
4. On line 58 of About.jsx, change to :
```
                  <span className="d-flex mt-3">
                    <a
                      target="_blank"
                      rel="noopener noreferrer"
                      className="cta-btn cta-btn--resume"
                      href={File}
                    >
                      Resume
                    </a>
                  </span>
```

5. In data.js, change to `resume: "My-Resume.pdf"` under aboutData. I'm pretty sure you can put anything here as long as it's not empty so the button shows up, I haven't tested it.

Browser's download option is in the top right when clicked.

**Comment by cobidev** [comment]
@aditya2712 can we talk on this thread: https://github.com/cobidev/simplefolio/issues/9 ?

@hadi-mirza please send that approach as an issue for the Gatsby Simplefolio repository.

Hence I will close this issue. Let's talk about his on: https://github.com/cobidev/simplefolio/issues/9

**Comment by aditya2712** [comment]
Ok sure!! @cobidev

**Comment by hadi-mirza** [comment]
@cobidev I apologize, I will forward this to the Gatsby version from now on!
