### ISSUE TITLE
download resume option

### ISSUE THREAD

**Issue by ap-dev1** [cobidev/simplefolio#61]
How can I have my visitors DOWNLOAD my resume? Is there a way for that? If it isn't, can you spell out "there isn't, your resume MUST be served from a link..", or something like that? Thanks.

**Comment by hadi-mirza** [comment]
I've only tested this on Chrome.

1. Add this in gatsby-config inside plugins array with the other resolve objects:
```
   {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'pdf',
        path: '${__dirname}/src/pdf/',
      },
    },
```

2. Create directory in `src` folder called `pdf` and drop your resume in there: `/src/pdf/My-Resume.pdf`
3. In `/src/Components/About/About.jsx` add to the top of the page: `import File from '../../pdf/My-Resume.pdf'`
4. On line 58 of About.jsx, change to :
```
                  <span className="d-flex mt-3">
                    <a
                      target="_blank"
                      rel="noopener noreferrer"
                      className="cta-btn cta-btn--resume"
                      href={File}
                    >
                      Resume
                    </a>
                  </span>
```

5. In data.js, change to `resume: "My-Resume.pdf"` under aboutData. I'm pretty sure you can put anything here as long as it's not empty so the button shows up, I haven't tested it.

Browser's download option is in the top right when clicked.

**Comment by cobidev** [comment]
@ap-dev1 do you want this feature for Simplefolio V1 or Gatsby Simplefolio?

@hadi-mirza suggest a solution but for Gatsby version.

Let me know your response, if you already solved it or not. So I can start working on that feature and update the Documentation.

**Comment by cobidev** [comment]
@ap-dev1 Hi,

Let me know if you solved this or the status.

So I can close the issue.

**Comment by ap-dev1** [comment]
I remade the entire app but I forget to close the issue. Thank you for the reminder. Best, -a.
