### ISSUE TITLE
netlify deployment error

### ISSUE THREAD

**Issue by ashwinpillai** [cobidev/simplefolio#69]
8:28:36 PM: Build ready to start
8:28:37 PM: build-image version: 09c2cdcdf242cf2f57c9ee0fcad9d298fad9ad41
8:28:37 PM: build-image tag: v3.5.0
8:28:37 PM: buildbot version: 92401c20a786cb1d10de411d95c4bfae445aeadc
8:28:38 PM: Fetching cached dependencies
8:28:38 PM: Failed to fetch cache, continuing with build
8:28:38 PM: Starting to prepare the repo for build
8:28:38 PM: No cached dependencies found. Cloning fresh repo
8:28:38 PM: git clone https://github.com/ashwinpillai/resume
8:28:39 PM: Preparing Git Reference refs/heads/main
8:28:40 PM: Starting build script
8:28:41 PM: Installing dependencies
8:28:41 PM: Python version set to 2.7
8:28:42 PM: v12.18.0 is already installed.
8:28:43 PM: Now using node v12.18.0 (npm v6.14.4)
8:28:43 PM: Started restoring cached build plugins
8:28:43 PM: Finished restoring cached build plugins
8:28:43 PM: Attempting ruby version 2.7.1, read from environment
8:28:45 PM: Using ruby version 2.7.1
8:28:45 PM: Using PHP version 5.6
8:28:45 PM: Started restoring cached node modules
8:28:45 PM: Finished restoring cached node modules
8:28:45 PM: Installing NPM modules using NPM version 6.14.4
8:29:03 PM: > node-sass@4.14.1 install /opt/build/repo/node_modules/node-sass
8:29:03 PM: > node scripts/install.js
8:29:03 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-72_binding.node
8:29:04 PM: Download complete
8:29:04 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
8:29:04 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.14.1/linux-x64-72_binding.node
8:29:04 PM: > node-sass@4.14.1 postinstall /opt/build/repo/node_modules/node-sass
8:29:04 PM: > node scripts/build.js
8:29:05 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
8:29:05 PM: Testing binary
8:29:05 PM: Binary is fine
8:29:06 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
8:29:06 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8:29:06 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
8:29:06 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8:29:06 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
8:29:06 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8:29:06 PM: added 962 packages from 532 contributors and audited 967 packages in 19.502s
8:29:06 PM: 50 packages are looking for funding
8:29:06 PM:   run `npm fund` for details
8:29:06 PM: found 0 vulnerabilities
8:29:06 PM: NPM modules installed
8:29:07 PM: Started restoring cached go cache
8:29:07 PM: Finished restoring cached go cache
8:29:07 PM: go version go1.14.4 linux/amd64
8:29:07 PM: go version go1.14.4 linux/amd64
8:29:07 PM: Installing missing commands
8:29:07 PM: Verify run directory
8:29:09 PM: ​
8:29:09 PM: ┌─────────────────────────────┐
8:29:09 PM: │        Netlify Build        │
8:29:09 PM: └─────────────────────────────┘
8:29:09 PM: ​
8:29:09 PM: ❯ Version
8:29:09 PM:   @netlify/build 5.3.1
8:29:09 PM: ​
8:29:09 PM: ❯ Flags
8:29:09 PM:   deployId: 5fb3e51cb53fa82bd1696b10
8:29:09 PM:   mode: buildbot
8:29:09 PM: ​
8:29:09 PM: ❯ Current directory
8:29:09 PM:   /opt/build/repo
8:29:09 PM: ​
8:29:09 PM: ❯ Config file
8:29:09 PM:   No config file was defined: using default values.
8:29:09 PM: ​
8:29:09 PM: ❯ Context
8:29:09 PM:   production
8:29:09 PM: ​
8:29:09 PM: ┌───────────────────────────────────┐
8:29:09 PM: │ 1. Build command from Netlify app │
8:29:09 PM: └───────────────────────────────────┘
8:29:09 PM: ​
8:29:09 PM: $ npm run build
8:29:09 PM: > simplefolio@1.0.1 build /opt/build/repo
8:29:09 PM: > webpack --config webpack.prod.js
8:29:21 PM: Hash: e277526b2c823e8dfad6
8:29:21 PM: Version: webpack 4.44.2
8:29:21 PM: Time: 9805ms
8:29:21 PM: Built at: 11/17/2020 2:59:21 PM
8:29:21 PM:  4 assets
8:29:21 PM: Entrypoint vendor = vendor.16a91483182952ce1d4c.bundle.js
8:29:21 PM: Entrypoint main = main.fd790a426c9a8d7da599.css main.8d0c1fd70573612ffc7a.bundle.js
8:29:21 PM: [2] ./src/js/tilt.js 180 bytes {0} [built]
8:29:21 PM: [3] ./src/js/sr.js + 1 modules 1.86 KiB {0} [built]
8:29:21 PM:     | ./src/js/sr.js 1.73 KiB [built]
8:29:21 PM:     | ./src/js/assignProps.js 131 bytes [built]
8:29:21 PM: [4] ./src/vendor.js 58 bytes {1} [built]
8:29:21 PM: [6] (webpack)/buildin/global.js 472 bytes {1} [built]
8:29:21 PM: [7] ./src/index.js 425 bytes {0} [built]
8:29:21 PM: [9] ./src/style/main.scss 39 bytes {0} [built]
8:29:21 PM:     + 6 hidden modules
8:29:21 PM: Child HtmlWebpackCompiler:
8:29:21 PM:      2 assets
8:29:21 PM:     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
8:29:21 PM:     [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html 7.4 KiB {0} [built]
8:29:21 PM:     [2] ./src/assets/project.jpg 97 bytes {0} [built]
8:29:21 PM:         + 1 hidden module
8:29:21 PM:     ERROR in ./src/template.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html)
8:29:21 PM:     Module not found: Error: Can't resolve './assets/face.jpg' in '/opt/build/repo/src'     @ ./src/template.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html) 5:33-61
8:29:21 PM:     ERROR in ./src/template.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html)
8:29:21 PM:     Module not found: Error: Can't resolve './assets/pizza.jpg' in '/opt/build/repo/src'     @ ./src/template.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html) 4:33-62
8:29:21 PM: Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!src/style/main.scss:
8:29:21 PM:     Entrypoint mini-css-extract-plugin = *
8:29:21 PM:     [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/style/main.scss 151 KiB {0} [built]
8:29:21 PM:         + 1 hidden module
8:29:21 PM: npm ERR! code ELIFECYCLE
8:29:21 PM: npm ERR! errno 2
8:29:21 PM: npm ERR! simplefolio@1.0.1 build: `webpack --config webpack.prod.js`
8:29:21 PM: npm ERR! Exit status 2
8:29:21 PM: npm ERR!
8:29:21 PM: npm ERR! Failed at the simplefolio@1.0.1 build script.
8:29:21 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
8:29:21 PM: npm ERR! A complete log of this run can be found in:
8:29:21 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-11-17T14_59_21_242Z-debug.log
8:29:21 PM: ​
8:29:21 PM: ┌─────────────────────────────┐
8:29:21 PM: │   "build.command" failed    │
8:29:21 PM: └─────────────────────────────┘
8:29:21 PM: ​
8:29:21 PM:   Error message
8:29:21 PM:   Command failed with exit code 2: npm run build
8:29:21 PM: ​
8:29:21 PM:   Error location
8:29:21 PM:   In Build command from Netlify app:
8:29:21 PM:   npm run build
8:29:21 PM: ​
8:29:21 PM:   Resolved config
8:29:21 PM:   build:
8:29:21 PM:     command: npm run build
8:29:21 PM:     commandOrigin: ui
8:29:21 PM:     publish: /opt/build/repo/dist
8:29:21 PM: Caching artifacts
8:29:21 PM: Started saving node modules
8:29:21 PM: Finished saving node modules
8:29:21 PM: Started saving build plugins
8:29:21 PM: Finished saving build plugins
8:29:21 PM: Started saving pip cache
8:29:21 PM: Finished saving pip cache
8:29:21 PM: Started saving emacs cask dependencies
8:29:21 PM: Finished saving emacs cask dependencies
8:29:21 PM: Started saving maven dependencies
8:29:21 PM: Finished saving maven dependencies
8:29:21 PM: Started saving boot dependencies
8:29:21 PM: Finished saving boot dependencies
8:29:21 PM: Started saving go dependencies
8:29:21 PM: Finished saving go dependencies
8:29:24 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:29:24 PM: Failing build: Failed to build site
8:29:24 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
8:29:24 PM: Finished processing build request in 46.714865326s

**Comment by hadi-mirza** [comment]
I'm not hundred percent sure this is the issue but want to help.

Obviously the error lies here:
`Module not found: Error: Can't resolve './assets/face.jpg' in '/opt/build/repo/src' @ ./src/template.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html) 5:33-61
8:29:21 PM: ERROR in ./src/template.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html)
8:29:21 PM: Module not found: Error: Can't resolve './assets/pizza.jpg' in '/opt/build/repo/src' @ ./src/template.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html) 4:33-62`

Two things I need info on:

1. this "assets" folder, is this a new directory you've added yourself in the /src folder? If so, you need to make some changes to your gatsby-config.js file which I can help provide.

2. Have you tried 'npm run serve' on your machine? It looks like there's an issue with paths for those jpg files when building the development. Running this command will show you errors or success in the build which will be accessible on your local machine on port 9000 instead of Netlify.

**Comment by ashwinpillai** [comment]
Issue resolved it was a problem of extension of assests

**Comment by hadi-mirza** [comment]
Great to hear that @ashwinpillai

**Comment by cobidev** [comment]
Thanks you @hadi-mirza 🎉

Hence I will close this issue.
