### ISSUE TITLE
How are static files used here?

### ISSUE THREAD

**Issue by alexeigud** [cobidev/simplefolio#72]
I suggest you describe in the readme, how static files are used here so that users leveraging this repo are able to implement features with more ease. For example, creating an Open Graph Protocol Object.

**Comment by cobidev** [comment]
Hello @alexeigud I hope you're doing well!

I wanted to keep this version of Simplefolio the more simple I can. If you want to add additional features that may add more static file types, I suggest you to fork my project and tweak it with your own version or sending me a Pull Request so I can review it.
