### ISSUE TITLE
Readme Instructions on resume

### ISSUE THREAD

**Issue by rckatz** [cobidev/simplefolio#9]
Hi @cobidev, I just used your project as part of Andrei's course and I was wondering if you could update the readme with steps on how to add a resume to the site? I threw a PDF into the src folder and added it to the resume <a> href and I get nothing (probably something I did) but I think steps for everyone would help.
Thanks!

**Comment by cobidev** [comment]
Hello @rckatz, I think you're getting problems because webpack doesn't know about PDF files. I'll check if I can solve that issue on the webpack config. Thank you for notice that issue, I'll let you know once I resolve this issue.

**Comment by rckatz** [comment]
@cobidev,
How I eventually got it to work was adding an import line in the index.js file so it could "see" the PDF, added a function to add that link to the resume button href, and removed the [hash] from the file-loader, name line in the webpack.common file. (was something like [name][hash].[ext]) file-loader had PDF listed but it wasn't picking it up in the asset folder for whatever reason.

**Comment by rckatz** [comment]
index.js:
```
import MyResume from './assets/sam-poe-resume.pdf';
...
function addResume(MyResume){
  const elements = document.getElementsByClassName('.cta-btn--resume');
  for(let el of elements){
    el.href = url(MyResume);
  }
}initSr();
initTilt();
addResume();
```

webpack.common.js:
```
module: {
    rules: [
      {
        test: /\.html$/,
        use: ['html-loader']
      },
      {
        test: /\.(jpg|jpeg|png|gif|svg|pdf)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]', //removed [hash]
              outputPath: 'assets'
            },
          },
        ],
      },
    ],
  },
```

**Comment by frankoadeleye** [comment]
Very helpful. Thanks
