### ISSUE TITLE
Creating a new section on simplefolio.

### ISSUE THREAD

**Issue by rolexroy** [cobidev/simplefolio#95]
Hello, I'd like to create a new section for 'skills' in the simplefolio. Kindly let me know how i can go about that. Thank you.

**Comment by cobidev** [comment]
@rolexroy Hi!

I would copy the existing HTML sections, and modify it a little bit, it's up to you if you want to be creative with the portfolio template!

But as I said, after copying the section, I would create the styles for that section if a way more different than the others.

Hence I will close this issue!
